services:
  movies-copy-backup:
    container_name: movies-copy-backup
    cpus: 5.0
    image: abesesr/movies:okd-copy-backup
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/processors.add_fields.fields.abes_appli: movies
      co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-copy-backup
      co.elastic.logs/processors.add_fields.target: ''
      com.centurylinklabs.watchtower.scope: movies-watchtower-scope
    mem_limit: 5g
    memswap_limit: 5g
    networks:
      default: null
    profiles:
    - test
    restart: unless-stopped
    secrets:
      - kubeconfig
    environment:
      PROJECT: movies-docker-beta
      KUBECONFIG: /run/secrets/kubeconfig/kubeconfig
secrets:
  kubeconfig:
    file: kubeconfig.txt

